[package]
name = "libplugin-sys"
version = "0.1.0"
authors = ["Vegard Sandengen <vegardsa@spacetec.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
